### ISSUE TITLE
Update config_patches.plist

### ISSUE THREAD

**Issue by benbaker76** [Sniki/OS-X-USB-Inject-All#5]
[config_patches.plist](https://github.com/headkaze/Hackintool/blob/master/Resources/USB/config_patches.plist)

**Comment by Sniki** [comment]
> [config_patches.plist](https://github.com/headkaze/Hackintool/blob/master/Resources/USB/config_patches.plist)

Thanks @headkaze , will add it soon, including 0.7.5 release.

**Comment by Sniki** [comment]
@headkaze i did update project to 0.7.5 and reverted the problems that i accidentally introduced in 0.7.4 where the kext turned not functional.

i did exclude the XHCI to XHC rename as that is natively supported on the kext.

A few changes that i plan to do on next update are:
- Test whether i can incorporate the EHC1 and EHC2 and XHC1 name matches so those renames are not necessary and supported natively from USBInjectAll.kext.
- That way we don't brake compatibility with other Operating Systems and also can use the XHCIPortLimit quirk of OpenCore to detect all ports without having the need for above renames.
- You can then also update Hackintool to build USBPorts.kext with EHC1 and EHC2 names instead of EH01 and EH02.

Respect,
Sniki
